# 4.8 Grouping Data & Aggregating Variables

## This script contains the following points:

### 1. Find the aggregated mean of the 'order_number' column grouped by 'department_id' for the entire 'ords_prods_merge' dataframe

### 2. How do the results for the entire dataframe differ from those of the subset?

### 3. Create a loyalty flag for exciting customers using the transform() and loc() functions

### 4. Determine whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers

### 5. Find the average prices of items people are buying to determine different types of spenders

### 6. Determine frequent versus non-frequent customers.

### 7. Export dataframe as a pickle file to "Prepared Data" folder

# 01. Importing libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os
import warnings

In [2]:
warnings.filterwarnings('ignore')

# 02. Importing data

In [3]:
df = pd.read_csv(r'C:\Users\Priya\27-02-2024 Instacart Basket Analysis\02 Data\Original Data\orders.csv', index_col = False)

In [4]:
path = r'C:\Users\Priya\27-02-2024 Instacart Basket Analysis'

In [5]:
path

'C:\\Users\\Priya\\27-02-2024 Instacart Basket Analysis'

In [6]:
# Import ords_prods_merge dataframe
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge.pkl'))

In [7]:
ords_prods_merge.shape

(32404859, 25)

## 1. Find the aggregated mean of the 'order_number' column grouped by 'department_id' for the entire 'ords_prods_merge' dataframe

In [7]:
# Split the data into group based on "department_id".
# Apply the aggregate function to each group to obtain the mean values for the "order_number" colimn.
ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

## 2. How do the results for the entire dataframe differ from those of the subset?

### There are 21 department_id groups in the entire dataframe when compared to 7 in the subset.

### The mean values of order_number vary in both the grouos as the count of records are different in both the datasets.

## 3. Create a loyalty flag for exciting customers using the transform() and loc() functions

In [8]:
# Split the data into groups based on the "user_id" column.
# Apply the transform() function on the "order_number" column to generate the maximum orders for each user.
# Create a new column, "max_order", into which you'll place the results of ypur aggregation.
ords_prods_merge['max_order'] = ords_prods_merge.groupby('user_id')['order_number'].transform(np.max)

In [9]:
# Check the newly created column 'max_order'
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average spent,spending flag,regularity,order frequency flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer

In [30]:
# Create a loyalty flag that assigns a loyalty label to a user ID based on its corresponding max order value.
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [31]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [32]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [33]:
# Look the value count of each loyalty_flag
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [34]:
# Check the newly added column 'loyalty_flag'
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average spent,spending flag,regularity,order frequency flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer

## 4. Determine whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers

In [35]:
# Group the customers by 'loyalty_flag' and calculate mean, min and max on prices spent on products to understand the spending habits of the three types of customers identified.
ords_prods_merge.groupby('loyalty_flag').agg({'prices' : ['mean', 'min', 'max']})

                    prices
                      mean  min   max
loyalty_flag
Loyal customer    7.772831  1.0  25.0
New customer      7.800320  1.0  25.0
Regular customer  7.797431  1.0  25.0

### The above results shows that the New customers spent the most, followed by Regular customers and then the Loyal customers.

## 5. Find the average prices of items people are buying to determine different types of spenders

In [16]:
# Split the data into groups based on the "user_id" column.
# Apply the transform() function on the "prices" colimn to generate the average price accross all orders for each user.
# Assign the average price values to a variable 'average spent'.
ords_prods_merge['average spent'] =  ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [17]:
# Create a new column, "spending flag", into which the label based on aggregation is assigned.
ords_prods_merge.loc[ords_prods_merge['average spent'] >= 10, 'spending flag'] = 'High spender'

In [18]:
ords_prods_merge.loc[ords_prods_merge['average spent'] < 10, 'spending flag'] = 'Low spender'

In [19]:
# This command tells pandas not to assign any options regarding the maximum number of rows to display.
# For ex, when using head() function to display more records say, head(100), All 100 rows would display if the below code is run.
pd.options.display.max_rows = None

In [20]:
# Look at the mean values in 'spending flag' column for each user.
ords_prods_merge[['user_id','prices','average spent','spending flag']].head(100)

    user_id  prices  average spent spending flag
0       138     5.8       6.935811   Low spender
1       138     5.8       6.935811   Low spender
2       709     5.8       7.930208   Low spender
3       764     5.8       4.972414   Low spender
4       764     5.8       4.972414   Low spender
5       777     5.8       6.935398   Low spender
6       825     5.8       5.957576   Low spender
7       910     5.8       6.680000   Low spender
8      1052     5.8       7.162500   Low spender
9      1052     5.8       7.162500   Low spender
10     1379     5.8       5.813636   Low spender
11     1480     5.8       5.081633   Low spender
12     1480     5.8       5.081633   Low spender
13     1480     5.8       5.081633   Low spender
14     1494     5.8       6.803797   Low spender
15     1494     5.8       6.803797   Low spender
16     1494     5.8       6.803797   Low spender
17     1540     5.8       6.607122   Low spender
18     1540     5.8       6.607122   Low spender
19     1540     5.8       6.607122   Low spender
20     1540     5.8       6.607122   Low spender
21     1540     5.8       6.607122   Low spender
22     1540     5.8       6.607122   Low spender
23     1540     5.8       6.607122   Low spender
24     1540     5.8       6.607122   Low spender
25     1540     5.8       6.607122   Low spender
26     1540     5.8       6.607122   Low spender
27     1540     5.8       6.607122   Low spender
28     1540     5.8       6.607122   Low spender
29     1540     5.8       6.607122   Low spender
30     1540     5.8       6.607122   Low spender
31     1540     5.8       6.607122   Low spender
32     1540     5.8       6.607122   Low spender
33     1540     5.8       6.607122   Low spender
34     1598     5.8       7.123529   Low spender
35     1598     5.8       7.123529   Low spender
36     1598     5.8       7.123529   Low spender
37     1647     5.8       4.853521   Low spender
38     1647     5.8       4.853521   Low spender
39     1647     5.8       4.853521   Low spender
40     1647     5.8       4.853521   Low spender
41     1647     5.8       4.853521   Low spender
42     2833     5.8       7.377143   Low spender
43     2850     5.8       8.054153   Low spender
44     2857     5.8       8.353793   Low spender
45     3010     5.8       6.452800   Low spender
46     3029     5.8       7.960606   Low spender
47     3395     5.8       6.322222   Low spender
48     3904     5.8       7.511111   Low spender
49     4006     5.8       7.441100   Low spender
50     4006     5.8       7.441100   Low spender
51     4006     5.8       7.441100   Low spender
52     4006     5.8       7.441100   Low spender
53     4006     5.8       7.441100   Low spender
54     4122     5.8       7.598765   Low spender
55     4141     5.8       6.033333   Low spender
56     4343     5.8       7.393939   Low spender
57     4553     5.8       5.715789   Low spender
58     4845     5.8       7.229630   Low spender
59     6866     5.8       4.807143   Low spender
60     7275     5.8       4.620833   Low spender
61     7669     5.8       9.106757   Low spender
62     7669     5.8       9.106757   Low spender
63     7669     5.8       9.106757   Low spender
64     7981     5.8       7.115714   Low spender
65     7981     5.8       7.115714   Low spender
66     7981     5.8       7.115714   Low spender
67     7981     5.8       7.115714   Low spender
68     7981     5.8       7.115714   Low spender
69     8703     5.8       6.593459   Low spender
70     8723     5.8       5.677397   Low spender
71     8735     5.8       5.850000   Low spender
72     9293     5.8      11.857143  High spender
73     9293     5.8      11.857143  High spender
74     9467     5.8       7.709091   Low spender
75     9694     5.8       7.075354   Low spender
76     9694     5.8       7.075354   Low spender
77     9694     5.8       7.075354   Low spender
78     9694     5.8       7.075354   Low spender
79     9694     5.8       7.075354   Low spender
80     9694     5.8       7.075354   Low spender
81     9694     5.8       7.075354   Low spender
82     9694     5.8       7.075354   Low spender
83     9694     5.8       7.075354   Low spender
84     9694     5.8       7.075354   Low spender
85     9694     5.8       7.075354   Low spender
86     9848     5.8       8.312203   Low spender
87    10113     5.8       8.769565   Low spender
88    10315     5.8      10.188889  High spender
89    10479     5.8       7.779775   Low spender
90    10708     5.8       7.777403   Low spender
91    10708     5.8       7.777403   Low spender
92    10789     5.8       6.097701   Low spender
93    10789     5.8       6.097701   Low spender
94    10789     5.8       6.097701   Low spender
95    10831     5.8       7.494286   Low spender
96    11119     5.8       5.878641   Low spender
97    11186     5.8       6.618085   Low spender
98    11243     5.8       5.927149   Low spender
99    11448     5.8       5.981250   Low spender

In [21]:
# Look at the value of new flag column.
ords_prods_merge['spending flag'].value_counts(dropna = False)

spending flag
Low spender     32285165
High spender      119694
Name: count, dtype: int64

## 6. Determine frequent versus non-frequent customers.

In [22]:
# Group records by 'user_id', calculate median of 'days_since_prior_order' and assign the aggregation result to variable 'regularity'.
ords_prods_merge['regularity'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [23]:
# Based on the 'regularity' value the new column 'order frequency flag' gets appropiate label.
ords_prods_merge.loc[ords_prods_merge['regularity'] > 20, 'order frequency flag'] = 'Non-frequent customer'

In [24]:
ords_prods_merge.loc[(ords_prods_merge['regularity'] > 10) & (ords_prods_merge['regularity'] <= 20), 'order frequency flag'] = 'Regular customer'

In [25]:
ords_prods_merge.loc[ords_prods_merge['regularity'] <= 10, 'order frequency flag'] = 'Frequent customer'

In [26]:
# Look at the newly added flag column.
ords_prods_merge[['user_id','regularity','order frequency flag']].head(100)

    user_id  regularity   order frequency flag
0       138         8.0      Frequent customer
1       138         8.0      Frequent customer
2       709         8.0      Frequent customer
3       764         9.0      Frequent customer
4       764         9.0      Frequent customer
5       777        11.0       Regular customer
6       825        20.0       Regular customer
7       910         6.0      Frequent customer
8      1052        10.0      Frequent customer
9      1052        10.0      Frequent customer
10     1379        20.0       Regular customer
11     1480         7.0      Frequent customer
12     1480         7.0      Frequent customer
13     1480         7.0      Frequent customer
14     1494         7.0      Frequent customer
15     1494         7.0      Frequent customer
16     1494         7.0      Frequent customer
17     1540         7.0      Frequent customer
18     1540         7.0      Frequent customer
19     1540         7.0      Frequent customer
20     1540         7.0      Frequent customer
21     1540         7.0      Frequent customer
22     1540         7.0      Frequent customer
23     1540         7.0      Frequent customer
24     1540         7.0      Frequent customer
25     1540         7.0      Frequent customer
26     1540         7.0      Frequent customer
27     1540         7.0      Frequent customer
28     1540         7.0      Frequent customer
29     1540         7.0      Frequent customer
30     1540         7.0      Frequent customer
31     1540         7.0      Frequent customer
32     1540         7.0      Frequent customer
33     1540         7.0      Frequent customer
34     1598         2.0      Frequent customer
35     1598         2.0      Frequent customer
36     1598         2.0      Frequent customer
37     1647        25.0  Non-frequent customer
38     1647        25.0  Non-frequent customer
39     1647        25.0  Non-frequent customer
40     1647        25.0  Non-frequent customer
41     1647        25.0  Non-frequent customer
42     2833        13.0       Regular customer
43     2850         7.0      Frequent customer
44     2857        11.0       Regular customer
45     3010         7.0      Frequent customer
46     3029        28.0  Non-frequent customer
47     3395        18.0       Regular customer
48     3904        21.0  Non-frequent customer
49     4006         7.0      Frequent customer
50     4006         7.0      Frequent customer
51     4006         7.0      Frequent customer
52     4006         7.0      Frequent customer
53     4006         7.0      Frequent customer
54     4122         7.0      Frequent customer
55     4141        30.0  Non-frequent customer
56     4343        30.0  Non-frequent customer
57     4553        30.0  Non-frequent customer
58     4845        20.0       Regular customer
59     6866        30.0  Non-frequent customer
60     7275        12.0       Regular customer
61     7669         5.0      Frequent customer
62     7669         5.0      Frequent customer
63     7669         5.0      Frequent customer
64     7981         6.0      Frequent customer
65     7981         6.0      Frequent customer
66     7981         6.0      Frequent customer
67     7981         6.0      Frequent customer
68     7981         6.0      Frequent customer
69     8703         1.0      Frequent customer
70     8723         6.0      Frequent customer
71     8735        27.0  Non-frequent customer
72     9293        30.0  Non-frequent customer
73     9293        30.0  Non-frequent customer
74     9467        30.0  Non-frequent customer
75     9694        10.0      Frequent customer
76     9694        10.0      Frequent customer
77     9694        10.0      Frequent customer
78     9694        10.0      Frequent customer
79     9694        10.0      Frequent customer
80     9694        10.0      Frequent customer
81     9694        10.0      Frequent customer
82     9694        10.0      Frequent customer
83     9694        10.0      Frequent customer
84     9694        10.0      Frequent customer
85     9694        10.0      Frequent customer
86     9848        11.0       Regular customer
87    10113        12.0       Regular customer
88    10315        11.0       Regular customer
89    10479        14.5       Regular customer
90    10708        14.0       Regular customer
91    10708        14.0       Regular customer
92    10789         7.0      Frequent customer
93    10789         7.0      Frequent customer
94    10789         7.0      Frequent customer
95    10831        23.0  Non-frequent customer
96    11119        13.0       Regular customer
97    11186         6.0      Frequent customer
98    11243         6.0      Frequent customer
99    11448        14.0       Regular customer

In [27]:
# Check the all new column added
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average spent,spending flag,regularity,order frequency flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer

In [28]:
# Look at the value count of the new flag column.
ords_prods_merge['order frequency flag'].value_counts(dropna = False)

order frequency flag
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
nan                             5
Name: count, dtype: int64

## 7. Export dataframe as a pickle file to "Prepared Data" folder

In [29]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge.pkl'))